### ISSUE TITLE
`styles.css` changes triggers true hot reload instead of full rebuild

### ISSUE THREAD

**Issue by huunab** [huunab/blazor-tailwindcss-template#2]
### Description

Right now, changes on `styles.css` will trigger a full reload when executing the project with `dotnet watch`, ideally it should execute a true hot reload.

### Taks

- [x] changes on `styles.css` executes true hot reload
- [x] changes on any `.razor` files triggers a hot reload on `styles.css`
  - JIT-compiler emits only the necessary css for the directives used on `.razor` files, any time a new directive is added we should trigger a hot reload on styles.css

**Comment by barahonajm** [comment]
For now, this issue https://github.com/dotnet/aspnetcore/issues/31924 is blocking progress on this feature
